# Generated by Django 5.1.5 on 2026-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('telegram_channel_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram Channel ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notify_on_new_order', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('notify_on_status_change', models.BooleanField(default=True, verbose_name='Уведомлять о смене статуса')),
                ('notify_on_low_stock', models.BooleanField(default=True, verbose_name='Уведомлять о низком остатке')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='Порог низкого остатка')),
                ('daily_report_time', models.TimeField(default='09:00', verbose_name='Время ежедневного отчёта')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
