# Generated by Django 5.1.5 on 2026-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('chat_type', models.CharField(blank=True, max_length=50, verbose_name='Тип чата')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Username')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Telegram чат',
                'verbose_name_plural': 'Telegram чаты',
                'ordering': ['-registered_at'],
            },
        ),
    ]
