# Generated by Django 5.1.5 on 2026-02-27 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegramchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='daily_report_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время ежедневного отчёта'),
        ),
    ]
