# Generated by Django 5.1.5 on 2026-02-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('socket_match', 'Совпадение сокета CPU и материнки'), ('ram_type_match', 'Совпадение типа RAM и материнки'), ('ram_slots_limit', 'Лимит слотов RAM'), ('ram_max_capacity', 'Максимальный объём RAM'), ('form_factor_fit', 'Совместимость форм-фактора'), ('gpu_length_fit', 'Длина GPU в корпусе'), ('cooler_height_fit', 'Высота кулера в корпусе'), ('psu_wattage_check', 'Мощность БП'), ('cooler_socket_match', 'Совместимость кулера и сокета'), ('m2_slots_limit', 'Лимит слотов M.2')], max_length=30, unique=True, verbose_name='Тип правила')),
                ('is_hard', models.BooleanField(default=True, verbose_name='Жёсткое ограничение')),
                ('message_template', models.TextField(verbose_name='Шаблон сообщения')),
            ],
            options={
                'verbose_name': 'Правило совместимости',
                'verbose_name_plural': 'Правила совместимости',
            },
        ),
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название сборки')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ сессии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершена'), ('ordered', 'Заказана')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая цена')),
                ('assembly_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена сборки')),
                ('ai_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка AI')),
                ('ai_comment', models.TextField(blank=True, verbose_name='Комментарий AI')),
                ('is_preset', models.BooleanField(default=False, verbose_name='Готовая сборка')),
                ('preset_label', models.CharField(blank=True, max_length=100, verbose_name='Тип сборки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Конфигурация ПК',
                'verbose_name_plural': 'Конфигурации ПК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('cpu', 'Процессор'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('gpu', 'Видеокарта'), ('ssd', 'SSD'), ('hdd', 'HDD'), ('psu', 'Блок питания'), ('case', 'Корпус'), ('cooler', 'Кулер/СЖО'), ('extra', 'Дополнительно')], max_length=20, verbose_name='Тип компонента')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_addition', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при добавлении')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Компонент конфигурации',
                'verbose_name_plural': 'Компоненты конфигурации',
            },
        ),
    ]
