# Generated by Django 5.1.5 on 2026-02-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcconfiguration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='configurations/', verbose_name='Фото сборки'),
        ),
    ]
