# Generated by Django 5.1.5 on 2026-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('assembling', 'Собирается'), ('shipping', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
